# Generated by Django 4.1.3 on 2022-11-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "book_outlet",
            "0003_book_author_book_is_bestselling_alter_book_rating_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=55),
        ),
    ]
